[
 ["""Elephants are animals. Elephants are animals?""", True],
 ["""Elephants are animals. John is an elephant. John is an animal?""", True],
 ["""Elephants are not birds. John is an elephant. John is not a bird?""", True],
 ["""Elephants are not birds. John is an elephant. John is a bird?""", False],
 ["""John is a man or not a man?""", True],
 ["""John is a man and not a man?""", False],
 ["""John is tall or not tall?""", True],
 ["""John is tall and not tall?""", False],
 ["""John is a tall man and not a tall man?""", False],
 ["""John is a tall man or not a tall man?""", None],
 ["""John has a car or does not have a car?""", True],
 ["""John has a car and does not have a car?""", False],
 ["""John has a car?""", None],
 ["""John is in Estonia or is not in Estonia?""", True],
 ["""John is in Estonia and is not in Estonia?""", False],
 ["""John is in Estonia?""", None],
 ["""John was yellow. John was yellow?""", True],
 ["""John was yellow. John was nice?""", None],
 ["""John was yellow. A man was nice?""", None],
 ["""A man was yellow. A man was yellow?""", True],
 ["""A man was yellow. A man was nice?""", None],
 ["""A man was yellow. John was nice?""", None],
 ["""Elephants are animals. Elephants are animals?""", True],
 ["""Elephants are animals. Some elephant is an animal?""", True],
 ["""Elephants are animals. All elephants are animals?""", True],
 ["""Elephants are animals. John is an animal?""", None],
 ["""Elephants are animals. Elephants are not animals?""", False],
 ["""Elephants are animals. Some elephants are not animals?""", False],
 ["""Elephants are animals. All elephants are not animals?""", False],
 ["""All elephants are animals. Elephants are animals?""", True],
 ["""All elephants are animals. Some elephant is an animal?""", True],
 ["""All elephants are animals. John is an animal?""", None],
 ["""All elephants are animals. Elephants are not animals?""", False],
 ["""All elephants are animals. Some elephants are not animals?""", False],
 ["""All elephants are animals. All elephants are not animals?""", False],
 ["""Some elephants are animals. Elephants are animals?""", None],
 ["""Some elephants are animals. Some elephant is an animal?""", True],
 ["""Some elephants are animals. All elephants are animals?""", None],
 ["""Some elephants are animals. John is an animal?""", None],
 ["""Some elephants are animals. Elephants are not animals?""", None],
 ["""Some elephants are animals. Some elephants are not animals?""", None],
 ["""Some elephants are animals. All elephants are not animals?""", None],
 ["""Some elephants are not animals. All elephants are animals?""", False],
 ["""All elephants are not animals. No elephant is an animal?""", None],
 ["""No elephant is an animal. No elephant is an animal?""", True],
 ["""No elephant is an animal. Some elephant is an animal?""", False],
 ["""It is not true that all big yellow cats are strong. Some yellow cats are not strong?""", True],
 ["""It is not true that all big yellow cats are strong. Some red cats are not strong?""", None],
 ["""It is not true that some big yellow cats are strong. All big yellow cats are not strong?""", True],
 ["""John likes all boxers. Mike is a boxer. John likes Mike?""", True],
 ["""Bears eat all boxers. Mike is a boxer. Greg is a bear. Greg eats Mike?""", True],
 ["""Bears eat most boxers. Mike is a boxer. Greg is a bear. Bears eats Greg?""", None],
 ["""Bears eat all boxers. Mike is a boxer. Bears eat boxers?""", True],
 ["""Bears eat some boxers. Mike is a boxer. Bears eat Mike?""", None],
 ["""John likes some boxers. Mike is a boxer. John likes Mike?""", None],
 ["""The red square has a nail. A blue square has a hole. A square has a nail?""", True],
 ["""The red square has a nail. A blue square has a hole. A square has a hole?""", True],
 ["""The red square has a nail. A blue square has a hole. A square has a dot?""", None],
 ["""The red square has a nail. A blue square has a hole. A red square has a nail?""", True],
 ["""The red square has a nail. A blue square has a hole. A blue square has a hole?""", True],
 ["""The red square has a nail. A blue square has a hole. A red square has a hole?""", None],
 ["""The red square is nice. A blue square is cool. A square is cool?""", True],
 ["""The red square is nice. A blue square is cool. A square is nice?""", True],
 ["""The red square is nice. A blue square is cool. A square is empty?""", None],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is an elephant. John is a toy?""", True],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is a fox. John is a good toy?""", True],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is a rabbit. John is an animal?""", True],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is a rabbit. John is an animal and a toy?""", True],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is a rabbit. John is an animal or a toy?""", True],
 ["""Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is a bird?""", False],
 ["""Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is not a bird?""", True],
 ["""Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is a small fish?""", False],
 ["""Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is a fish?""", None],
 ["""Elephants, foxes and rabbits are nice animals and good toys. John is an elephant. John is a red toy?""", None],
 ["""Elephants and sparrows are animals or birds. John is a sparrow. John is a bird. John is an animal?""", False],
 ["""Elephants and sparrows are animals or birds. John is a sparrow. Sparrows are birds. John is not an animal?""", True],
 ["""Elephants and sparrows are animals or birds. John is a sparrow. John is a bird. John is an animal or a bird?""", True],
 ["""Elephants and sparrows are animals or birds. John is a sparrow. John is a bird. John is an elephant?""", None],
 ["""Elephants or sparrows are animals. John is a sparrow. John is an animal?""", None],
 ["""Elephants or sparrows are animals. John is an elephant. Sparrows are not animals. John is an animal?""", True],
 ["""If animal or bird is nice and simple, it is cute. John is cute?""", None],
 ["""If animal or bird is nice and simple, it is cute. John is a nice and simple animal. John is cute?""", True],
 ["""If animal or bird is nice and simple, it is cute. John is a nice and simple bird. John is cute?""", True],
 ["""If animal or bird is nice and simple, it is cute. John is a nice and simple fox. John is cute?""", None],
 ["""If animal or bird is nice and simple, it is cute. John is a nice animal. John is cute?""", None],
 ["""Elephants are animals. Birds are animals?""", None],
 ["""Elephants are animals. Birds are not animals?""", None],
 ["""Elephants are animals. Birds are nice animals?""", None],
 ["""Elephants are animals. Birds are not nice animals?""", None],
 ["""John is a red or black elephant. John is an elephant. John is red. John is black?""", False],
 ["""Big or strong elephants are nice. John is a big elephant. John is nice?""", True],
 ["""Big or strong elephants are nice. John is a big elephant. John is strong. John is nice?""", True],
 ["""Big or strong elephants are nice. John is an elephant. John is nice?""", None],
 ["""Big and strong elephants are nice. John is a big elephant. John is a strong elephant. John is nice?""", True],
 ["""Yellow and green elephants are nice. John is an elephant. John is yellow and green. John is nice?""", True],
 ["""Big and strong elephants are nice. John is a strong elephant. John is nice?""", None],
 ["""Big and not strong elephants are nice. John is a big elephant. John is a not strong elephant. John is nice?""", True],
 ["""Elephants have trunks. Elephants have trunks?""", True],
 ["""No elephant has wings. No elephant has wings?""", True],
 ["""No elephants have wings. Some elephant has wings?""", False],
 ["""Elephants have no wings. Some elephant has wings?""", False],
 ["""Elephants have no wings. John has no wings?""", None],
 ["""All elephants have no wings. Some elephant has wings?""", False],
 ["""All elephants have no wings. John has no wings?""", None],
 ["""Some elephants have no wings. Some elephant has wings?""", None],
 ["""Some elephants have no wings. John has no wings?""", None],
 ["""No elephants have wings. All elephants do not have wings?""", True],
 ["""Elephants have trunks. John has a trunk?""", None],
 ["""All elephants have trunks. John has a trunk?""", None],
 ["""Some elephants have trunks. John has a trunk?""", None],
 ["""Elephants have a trunk. Birds have a trunk?""", None],
 ["""Elephants have a trunk. Birds do not have a trunk?""", None],
 ["""Elephants have long trunks and no wings. John is an elephant. John has a wing?""", False],
 ["""Elephants have long trunks and no wings. John is an elephant. John has no wing?""", True],
 ["""Elephants have long trunks and no wings. John is an elephant. John does not have a wing?""", True],
 ["""Elephants have long trunks and no wings. John is an elephant. John has a wing?""", False],
 ["""Elephants have long trunks and no wings. John is an elephant. John has a long trunk and no wing?""", True],
 ["""Elephants have long trunks. John is an elephant. John has a trunk?""", True],
 ["""Elephants have no trunks. John is an elephant. John has a trunk?""", False],
 ["""Elephants have trunks or tails. John is an elephant. John has no trunk. John has a tail?""", True],
 ["""Elephants have trunks or tails. John is an elephant. John has a tail and a trunk?""", False],
 ["""Elephants have trunks or tails. John is an elephant. John has a tail or a trunk?""", True],
 ["""Elephants have long or short trunks. John is an elephant. John does not have a long trunk. John has a short trunk?""", True],
 ["""Elephants have long or short trunks. John is an elephant. John has a trunk?""", True],
 ["""Elephants have long or short trunks. John is an elephant. John has a long trunk?""", None],
 ["""Elephants have no long red trunks. John is an elephant. John has a long red trunk?""", False],
 ["""Elephants have no long red trunks. John is an elephant. John has a long trunk?""", None],
 [""" Elephants have not red trunks. John is an elephant. John has a not red trunk?""", True],
 [""" Elephants have not red trunks. John is an elephant. John has a trunk?""", True],
 [""" Elephants have not red trunks. John is an elephant. John has a big trunk?""", None],
 [""" Elephants have long not red trunks. John is an elephant. John has a long not red trunk?""", True],
 [""" Elephants have long not red trunks. John is an elephant. John has a long trunk?""", True],
 [""" Elephants have long not red trunks. John is an elephant. John has a long black trunk?""", None],
 [""" Elephants have long not red trunks. John is an elephant. John has a not red trunk?""", True],
 [""" Elephants have long not big trunks. John is an elephant. John has a long not big trunk?""", True],
 [""" Elephants have long not big trunks. John is an elephant. John has a not big trunk?""", True],
 [""" Elephants have long not red trunks. John is an elephant. John has a long not small trunk?""", None],
 [""" Elephants have long not big trunks. John is an elephant. John has a long trunk?""", True],
 ["""Elephants do not have long red trunks. John is an elephant. John has a long red trunk?""", False],
 ["""Elephants do not have wings. John is an elephant. John has wings?""", False],
 ["""Elephants do not have wings. John is an elephant. John has a wing?""", False],
 ["""Elephants do not have long red wings. John is an elephant. John has a wing?""", None],
 ["""If an animal has a trunk, it is an elephant. John has a long trunk. John is an animal. 
      John is an elephant?""", True],
 ["""If an animal has a trunk, it is an elephant. John has a long trunk.  
      John is an elephant?""", None],
 ["""If an animal or bird has a tail, it is cute. John has a tail. John is cute?""", None],
 ["""If an animal or bird has a tail, it is cute. John has a tail. John is a fox. John is cute?""", None],
 ["""If an animal or bird has a tail, it is cute. John is an animal. John has a tail. John is cute?""", True],
 ["""If an animal or bird has a tail, it is cute. John is a bird. John has a tail. John is cute?""", True],
 ["""If an animal or bird has a tail, it is cute. John is a bird or an animal. John has a tail. John is cute?""", True],
 ["""If a bear is nice, it has a tail. John is a nice bear. John has a tail?""", True],
 ["""If a big bear is nice, it has a tail. John is a nice bear. John has a tail?""", None],
 ["""If a bear is nice and has a trunk, it has a tail. John is a nice bear. John has a trunk. John has a tail?""", True],
 ["""If cars are red, elephants are nice. Cars are red. Elephants are nice?""", True],
 ["""If cars are red, elephants are nice. Elephants are nice?""", None],
 ["""If some cars are red, elephants are nice. John is a red car. Elephants are nice?""", True],
 ["""If cars are red, elephants are nice. John is a red car. Elephants are nice?""", None],
 ["""If cars are green, elephants are nice. If elephants are nice, squirrels are red. Cars are green. Squirrels are red?""", True],
 ["""If cars have roofs, elephants are nice. Cars have roofs. Elephants are nice?""", True],
 ["""If cars have roofs, elephants are nice. John is a car. John has a roof. Elephants are nice?""", None],
 ["""If some cars have roofs, elephants are nice. John is a car. John has a roof. Elephants are nice?""", True],
 ["""If some car has a roof, elephants are nice. John is a car. John has a roof. Elephants are nice?""", True],
 ["""If X is cool then X is red. John is cool. Mike is red?""", None],
 ["""If X is cool then X is red. John is cool. John is red?""", True],
 ["""If X is cool and X is nice then X is red. John is nice and cool. John is red?""", True],
 ["""If X is cool and nice then X is red. John is nice and cool. John is red?""", True],
 ["""If X is cool and X is nice then X is red. Mike is nice. Mike is red?""", None],
 ["""If X is cool and X is nice then X is red. Mike is cool. Mike is red?""", None],
 ["""If X1 is a father of Y1, Y1 is a child of X1. 
      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1. 
      John is a father of Mike. Luke is a father of John. Luke is a grandfather of Mike?""", True],
 ["""If X1 is a father of Y1, Y1 is a child of X1. 
      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1. 
      John is a father of Mike. Luke is a father of John. 
      If X1 is a grandfather of Y1, Y1 is a grandchild of X1. Mike is a grandchild of Luke?""", True],
 ["""If X1 is a father of Y1, Y1 is a child of X1. 
      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1. 
      John is a father of Mike. Luke is a father of John. 
      If X1 is a grandfather of Y1, Y1 is a grandchild of X1. 
      If X1 is male and X1 is a grandchild of Y1, X1 is a grandson of Y1. 
      Mike is male. Mike is a grandson of Luke?""", True],
 ["""Tallinn is in Estonia. Estonia is not outside Europe. Earth contains Europe.  
       Estonia contains Tartu. Riga is not in Estonia. Riga is in Estonia?""", False],
 ["""It is true that elephants are animals. John is an elephant. John is an animal?""", True],
 ["""It is false that elephants are animals. John is an elephant. John is an animal?""", False],
 ["""It is not true that elephants are animals. John is an elephant. John is an animal?""", False],
 ["""It is not false that elephants are animals. John is an elephant. John is an animal?""", True],
 ["""It is true that John is a child of Mike. John is a child of Mike?""", True],
 ["""It is false that John is a child of Mike. John is a child of Mike?""", False],
 ["""It is true that Tallinn is in Estonia. Tallinn is in Estonia?""", True],
 ["""It is false that Tallinn is in Latvia. Tallinn is in Latvia?""", False],
 ["""John is an elephant with a probability 100 percent. John is an elephant?""", True],
 ["""John is an elephant with a probability 0 percent. John is an elephant?""", False],
 ["""John is an elephant with a probability 50 percent. John is an elephant?""", None],
 ["""Tallinn is in Latvia with a probability 50 percent. Tallinn is in Latvia?""", None],
 ["""Elephants have a trunk with a probability 50 percent. John is an elephant. John has a trunk?""", None],
 ["""Elephants are big. Young elephants are not big. 
      Mike is an elephant. John is a young elephant. Mike is big?""", True, ['default']],
 ["""Elephants are big. Young elephants are not big. 
      Mike is an elephant. John is a young elephant. John is big?""", False, ['default']],
 ["""Penguins are birds who do not fly. Birds fly. John is a penguin. John flies?""", False, ['default']],
 ["""Penguins are birds. Penguins do not fly. Birds fly. John is a penguin. John flies?""", False, ['default']],
 ["""Penguins are birds who do not fly. Birds fly. John is a bird. John flies?""", True, ['default']],
 ["""Penguins are birds. Penguins do not fly. Birds fly. John is a bird. John flies?""", True, ['default']],
 ["""Cars are nice. Cars are nice?""", True],
 ["""Cars are nice. Cars are not nice?""", False],
 ["""Red cars are not nice. Cars are nice. Cars are nice?""", True, ['default']],
 ["""Red cars are not nice. Cars are nice. Cars are not nice?""", False, ['default']],
 ["""Red cars are not nice. Cars are nice. Red cars are nice?""", False, ['default']],
 ["""Red cars are not nice. Cars are nice. Red cars are not nice?""", True, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. Cars have trunks?""", True, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. Red cars have trunks?""", False, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. Cars have a trunk?""", True, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. Red cars have a trunk?""", False, ['default']],
 ["""Red cars do not have trunks. Cars have a trunk. Cars have a trunk?""", True, ['default']],
 ["""Red cars do not have trunks. Cars have a trunk. Red cars have a trunk?""", False, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. John is a car. John has a trunk?""", True, ['default']],
 ["""Red cars do not have trunks. Cars have trunks. John is a red car. John has a trunk?""", False, ['default']],
 ["""Penguins are birds. Penguins do not fly. Birds fly. Birds fly?""", True, ['default']],
 ["""Penguins are birds. Penguins do not fly. Birds fly. Penguins fly?""", False, ['default']],
 ["""If a bear eats red berries, it is big. John eats berries. John is a bear. 
     John is big?""", None],
 ["""If a bear eats red berries, it is big. John eats red berries. John is a bear. 
     John is big?""", True],
 ["""If X1 eats berries, it is a bear. John eats red berries. John is a bear?""", True],
 ["""Bears eat berries. John is a bear. John eats berries?""", True],
 ["""Bears eat berries. John is a bear. John eats some berries?""", True],
 ["""Bears eat berries. John is a bear. John eats all berries?""", None],
 ["""Bears eat all berries. John is a bear. John eats all berries?""", True],
 ["""Some bears eat all berries. John is a bear. John eats berries?""", None],
 ["""Some bears eat all berries. Some bears eat berries?""", True],
 ["""Birds fly or swim. John is a bird. John does not fly. John swims?""", True],
 ["""Birds fly or swim. John is a bird. John swims?""", None],
 ["""Birds fly or do not swim. John is a bird. John does not fly. John swims?""", False],
 ["""Birds fly or do not swim. John is a bird. John never flies. John swims?""", False],
 ["""Birds do not fly and swim. John is a bird. John swims?""", False],
 ["""Birds do not fly and swim. John is a bird. John swims or flies?""", False],
 ["""Birds fly and swim. John is a bird. John swims and flies?""", True],
 ["""Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird. 
    John does not fly?""", True, ['default']],
 ["""Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird. 
    Mike flies?""", True, ['default']],
 ["""Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird. 
    John runs?""", None, ['default']],
 ["""Bears eat berries. Baby bears do not eat berries. John is a bear. 
     John eats berries?""", True, ['default']],
 ["""Bears eat berries. Baby bears do not eat berries. John is a baby bear. 
     John eats berries?""", False, ['default']],
 ["""Bears eat berries. Baby bears eat no berries. John is a baby bear. 
     John eats berries?""", False, ['default']],
 ["""Birds fly. No penguin can fly. Penguins are birds. John is a penguin. John can fly?""", False, ['default']],
 ["""Birds fly. No penguin can fly. Penguins are birds. John is a penguin. John flies?""", False, ['default']],
 ["""Birds can fly. No penguin can fly. Penguins are birds. John is a penguin. John can fly?""", False, ['default']],
 ["""Birds fly. No penguin can fly. Penguins are birds. John is a bird. John can fly?""", True, ['default']],
 ["""Birds fly. No penguin can fly. Penguins are birds. John is a bird. John flies?""", True, ['default']],
 ["""Birds can fly. No penguin can fly. Penguins are birds. John is a bird. John can fly?""", True, ['default']],
 ["""Bears eat berries in a forest. Bears eat berries in forest?""", True],
 ["""Bears eat berries in a forest. Bears do not eat berries in forest?""", False],
 ["""Bears eat berries in a forest. Bears eat berries in a field?""", None],
 ["""Bears eat berries in a forest. Bears eat berries?""", True],
 ["""Bears quickly eat berries in a forest. Bears eat berries?""", True],
 ["""Bears quickly eat berries in a forest. Bears quickly eat berries?""", True],
 ["""Bears quickly eat berries in a forest. Bears slowly eat berries?""", None],
 ["""Bears eat red berries in a forest. Bears eat red berries in forest?""", True],
 ["""Bears eat red berries in a forest. Bears eat berries in forest?""", True],
 ["""Bears eat red berries in a forest. Bears eat yellow berries in forest?""", None],
 ["""Bears do not eat red berries in a forest. Bears eat red berries in forest?""", False],
 ["""Bears eat berries in a deep forest. Bears eat berries?""", True],
 ["""Bears eat berries in a deep forest. Bears eat berries in a deep forest?""", True],
 ["""Bears eat berries in a deep forest. Bears eat berries in a forest?""", True],
 ["""Bears eat berries in a deep forest. Bears eat berries in a shallow forest?""", None],
 ["""Bears eat red berries in a deep forest. John is a bear. John eats red berries in a deep forest?""", True],
 ["""Bears eat red berries in a deep forest. John is a bear. John eats no berries?""", False],
 ["""Bears eat berries in a deep forest. John is a bear. John eats berries in a shallow forest?""", None],
 ["""Bears quickly eat berries in a deep forest. John is a bear. John quickly eats berries in a deep forest?""", True],
 ["""If a bear quickly eats berries in a deep forest, it is hungry. John is a bear.
     John quickly eats berries in a deep forest. John is hungry?""", True],
 ["""If a bear quickly eats berries in a deep forest, it is hungry. John is a bear.
     John eats berries in a deep forest. John is hungry?""", None],
 ["""If a bear quickly eats berries in a deep forest, it is hungry. John is a fox.
     John quickly eats berries in a deep forest. John is hungry?""", None],
 ["""John does not eat a carrot. John does not eat a carrot?""", True],
 ["""John does not eat a carrot. John eats a carrot?""", False],
 ["""John is not in a cave. John is not in a cave?""", True],
 ["""John is not in a cave. John is in a cave?""", False],
 ["""Big bears who have a trunk have a tail. John is a big bear. John has a trunk. John has a tail?""", True],
 ["""Big bears who have a trunk have a tail. John is a big bear. John has a nose. John has a tail?""", None],
 ["""Big bears who have a trunk have a tail. John is a bear. John has a trunk. John has a tail?""", None],
 ["""Big bears who are nice and have a trunk have a tail. John is a big bear. John has a trunk. John has a tail?""", None],
 ["""Big bears who are nice and have a trunk have a tail. John is a nice big bear. John has a trunk. John has a tail?""", True],
 ["""Big bears who are nice and who have a trunk have a tail. John is a big bear. John has a trunk. John has a tail?""", None],
 ["""Big bears who are nice and who have a trunk have a tail. John is a big bear. John is nice. John has a tail?""", None],
 ["""Big bears who are nice and who have a trunk have a tail. John is a nice big bear. John has a trunk. John has a tail?""", True],
 ["""Bears who are nice and have a long trunk have a tail. John is a nice big bear. John has a long trunk. John has a tail?""", True],
 ["""Bears who are nice and have a long trunk have a tail. John is a nice big bear. John has a trunk. John has a tail?""", None],
 ["""Bears who have a trunk are nice. John is a bear. John has a trunk. John is nice?""", True],
 ["""Bears who have a trunk are nice. John is a bear. John has a nose. John is nice?""", None],
 ["""Bears who are nice and eat berries have a tail. John is a nice big bear. John eats berries. John has a tail?""", True],
 ["""Bears who are nice and who eat berries have a tail. John is a nice big bear. John eats berries. John has a tail?""", True],
 ["""Bears who are nice and who eat berries have a tail. John is a nice big bear. John eats fish. John has a tail?""", None],
 ["""Bears who are big are strong. John is a big nice bear. John is strong?""", True],
 ["""Bears who are big are strong. John is a bear. John is strong?""", None],
 ["""Bears who have tails are strong. John is a big nice bear. John has a tail. John is strong?""", True],
 ["""Bears who have tails are strong. John is a big nice bear.  John is strong?""", None],
 ["""Bears who eat fish are strong. John eats fish. John is a bear. John is strong?""", True],
 ["""Bears who eat fish are strong. John is a bear. John is strong?""", None],
 ["""Bears who eat fish are strong. John eats carrots. John is a bear. John is strong?""", None],
 ["""Nice bears who have tails are strong. John is a nice bear. John has a tail. John is strong?""", True],
 ["""Nice bears who have tails are strong. John is a bear. John has a tail. John is strong?""", None],
 ["""Nice bears who have tails are strong. John is a nice bear. John has a head. John is strong?""", None],
 ["""Nice bears who are big are strong. John is a big nice bear. John is strong?""", True],
 ["""Nice bears who are big are strong. John is a nice bear. John is strong?""", None],
 ["""Nice bears who eat fish are strong. John is a nice bear. John eats fish. John is strong?""", True],
 ["""Nice bears who eat big fish are strong. John is a nice bear. John eats big fish. John is strong?""", True],
 ["""Nice bears who eat big fish are strong. John is a nice bear. John eats big carrots. John is strong?""", None],
 ["""Nice bears who eat big fish are strong. John is a nice bear. John eats fish. John is strong?""", None],
 ["""If a bear who is big is strong, it is nice. John is a big strong bear. John is nice?""", True],
 ["""If a bear who eats fish is strong, it is nice. John is a bear. John eats carrots. John is strong. John is nice?""", None],
 ["""If a bear who eats fish is strong, it is nice. John is a bear. John eats fish. John is nice?""", None],
 ["""Bears who eat fish which are big are strong. John is a bear. John eats fish. John is strong?""", None],
 ["""Bears who eat fish which are big are strong. John is a bear. John eats big apples. John is strong?""", None],
 ["""Bears eat fish who are strong. John is a bear. John eats strong fish?""", True],
 ["""Bears eat fish who are strong. John is a fox. John eats strong fish?""", None],
 ["""Bears eat fish who are strong. John is a bear. John eats red fish?""", None],
 ["""Bears eat red fish who are strong. John is a bear. John eats red strong fish?""", True],
 ["""Bears eat red fish who are strong. John is a bear. John eats yellow strong fish?""", None],
 ["""Bears eat red fish who are strong. John is a bear. John eats red fish?""", True],
 ["""Bears eat red fish who are strong. John is a bear. John eats yellow fish?""", None],
 ["""Bears eat red fish who are strong. John is a bear. John eats strong fish?""", True],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. John eats strong fish?""", True],
 ["""Bears who are nice eat fish who are strong. John is a bear. John eats strong fish?""", None],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. John eats yellow fish?""", None],
 ["""Bears who are nice and white eat fish who are strong and red. John is a nice white bear. John eats red strong fish?""", True],
 ["""Bears who are nice and white eat fish who are strong and red. John is a nice bear. John eats red strong fish?""", None],
 ["""Bears who are nice and white eat fish who are strong and red. John is a nice white bear. John eats yellow strong fish?""", None],
 ["""If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats strong fish. John is white. John is nice?""", True],
 ["""If a big bear who eats strong fish is white, it is nice. John is a bear. John eats strong fish. John is white. John is nice?""", None],
 ["""If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats strong fish. John is nice?""", None],
 ["""If a big bear who eats strong fish is white, it is nice. John is a big bear. John eats yellow fish. John is white. John is nice?""", None],
 ["""The big bear is strong. The bear is big?""", True],
 [""" The white mouse is strong. The mouse is white?""", True],
 [""" The big mouse is strong. The mouse is big?""", True],
 [""" The big mouse is strong. The mouse is a big mouse?""", True],
 ["""The big bear is strong. The bear is strong?""", True],
 ["""The big bear is strong. The big bear is strong?""", True],
 ["""The big bear is strong. The big bear is white?""", None],
 ["""The bear who is big is strong. The bear is big?""", True],
 [""" The white mouse is strong. The mouse is white?""", True],
 [""" The big mouse is strong. The mouse is a big mouse?""", True],
 ["""The bear who is big is strong. The bear is strong?""", True],
 ["""The bear who is big is strong. The big bear is strong?""", True],
 ["""The bear who is big is strong. The big bear is white?""", None],
 ["""The bear who is big eats fish. The bear who is big eats fish?""", True],
 ["""The bear who is white eats fish. The bear who is white eats fish?""", True],
 ["""The bear who was white ate a fish. The bear who was white ate a fish?""", True],
 ["""The bear who was white ate a fish. The bear ate a fish?""", True],
 ["""The bear who was white ate a fish. The white bear ate a fish?""", True],
 ["""Bears who were nice ate. Nice bears ate?""", True],
 ["""The bear who was nice ate. The bear ate?""", True],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish?""", True],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat tables?""", None],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat tables?""", None],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish?""", True],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish who are strong?""", True],
 ["""Bears who are nice eat fish who are strong. John is a nice bear. Nice bears eat strong fish?""", True],
 ["""The bear who was nice ate the fish who was strong. The bear who was nice ate the fish who was strong?""", True],
 ["""The bear who was nice ate the fish who was strong. The nice bear ate the strong fish?""", True],
 ["""The bear who was nice ate the fish who was strong. The bear who was nice ate the fish who was white?""", None],
 ["""The bear who was nice and white ate the fish who was big. The nice bear ate the big fish?""", True],
 ["""The bear who was white and ate a fish was cool. The white bear who ate a fish was cool?""", True],
 ["""The bear who was white and ate a fish was cool. The bear who ate a fish was cool?""", True],
 ["""The bear who was white and ate a fish was cool. The white bear who ate a fish was strong?""", None],
 ["""The bear who was white and ate a fish was cool. The black bear who ate a fish was cool?""", None],
 ["""The bear who was white and ate a big fish was cool. The white bear who ate a big fish was cool? """, True],
 ["""The bear who was white and ate a big fish was cool. The white bear who ate a fish was cool? """, True],
 ["""The bear who was white and ate a big fish was cool. The white bear who ate a strong fish was cool? """, None],
 ["""The nice bear who was white and ate a big fish was cool. The white nice bear who ate a big fish was cool? """, True],
 ["""The nice bear who was white and ate a big fish also ate berries. The white nice bear who ate a big fish also ate berries? """, True],
 ["""The nice bear who was white and ate a big fish also ate blue berries. The white nice bear who ate a big fish also ate blue berries? """, True],
 ["""The nice bear who was white and ate a big fish also ate blue berries. The white nice bear who ate a big fish also ate berries? """, True],
 ["""The nice bear who was white and ate a big fish also ate blue berries. The bear ate berries? """, True],
 ["""The nice bear who was white and ate a big fish also ate blue berries. The bear ate bread? """, None],
 ["""The bear who ate a big fish ate blue berries. The bear who ate a fish also ate blue berries?""", True],
 ["""The bear who ate a big fish ate blue berries. The bear who ate a fish ate big berries?""", None],
 ["""The bear who ate a big fish ate blue berries. John is big?""", None],
 ["""The bear who ate a big fish ate blue berries. John is blue?""", None],
 ["""The bear who ate a big fish ate blue berries. John is a fish?""", None],
 ["""John is very big. John is extremely big?""", True],
 ["""John is somewhat big. John is slightly big?""", True],
 ["""John is very big. John is very big?""", True],
 ["""John is very big. John is big?""", True],
 ["""John is very big. John is somewhat big?""", False],
 ["""John is big. John is very big?""", None],
 ["""John is big. John is big?""", True],
 ["""John is big. John is somewhat big?""", None],
 ["""John is somewhat big. John is very big?""", False],
 ["""John is somewhat big. John is big?""", True],
 ["""John is somewhat big. John is somewhat big?""", True],
 ["""John is big. John is not big?""", False],
 ["""John is very big. John is not very big?""", False],
 ["""John is very big. John is not big?""", False],
 ["""John is somewhat big. John is not somewhat big?""", False],
 ["""John is somewhat big. John is not big?""", False],
 ["""John is not very big. John is very big?""", False],
 ["""John is not very big. John is big?""", True],
 ["""A not very big bear is nice. The bear is a very big bear?""", False],
 ["""A not very big bear is nice. The bear is a big bear?""", True],
 ["""A not very big bear is nice. The bear is a somewhat big bear?""", None],
 ["""John is a not very big bear. John is a very big bear?""", False],
 ["""John is a not very big bear. John is a big bear?""", True],
 ["""John is not a very big bear. John is a bear?""", None],
 ["""John is not a very big bear. John is a big bear?""", None],
 ["""John is not a very big bear. John is a very big bear?""", False],
 ["""If John is not very big, John is nice. John is big. John is nice?""", None],
 ["""If John is not very big, John is nice. John is very big. John is nice?""", None],
 ["""If John is not very big, John is nice. John is somewhat big. John is nice?""", True],
 ["""A very big mouse is nice. The mouse is a very big mouse?""", True],
 ["""A very big mouse is nice. The mouse is a big mouse?""", True],
 ["""A very big mouse is nice. The mouse is a somewhat big mouse?""", False],
 ["""A very big mouse is nice. The mouse is very big?""", True],
 ["""A very big mouse is nice. The mouse is big?""", True],
 ["""A very big mouse is nice. The mouse is somewhat big?""", False],
 ["""If a bear is not very big, it is nice. John is a big bear. John is nice?""", None],
 ["""If a bear is not very big, it is nice. John is a very big bear. John is nice?""", None],
 ["""Frogs are small animals. John is a frog. John is a small animal?""", True],
 ["""Frogs are small animals. John is a frog. John is small?""", True],
 ["""Frogs are small. John is a frog. John is small?""", True],
 ["""Frogs are small. John is a frog. John is a small animal?""", None],
 ["""John is a big mouse. John is big?""", True],
 ["""John is a big mouse. John is a big mouse?""", True],
 ["""John is a big mouse. John is a big thing?""", None],
 ["""John had a car which Eve bought. John had a car which Eve bought?""", True],
 ["""John had a car which Eve bought. John had a car which Eve saw?""", None],
 ["""John had a car which Eve bought. John had a car which Mike bought?""", None],
 ["""John had a car which Mike bought. John had a car Mike bought?""", True],
 ["""John had a car which Eve bought. John had a car Eve saw?""", None],
 ["""John had a car which Eve bought. John had a car Mike bought?""", None],
 ["""John had a car Mike bought. John had a car Mike bought?""", True],
 ["""John had a car Eve bought. John had a car Mike bought?""", None],
 ["""John had a car Eve bought. John had a car Eve saw?""", None],
 ["""John had a car Eve bought. John had a car which Eve bought?""", True],
 ["""John had a car Eve bought. John had a car which Eve saw?""", None],
 ["""John had a car Eve bought. John had a car which Mike bought?""", None],
 ["""John had a car Eve bought. Eve bought a car?""", True],
 ["""John had a car Mary bought. Mary bought a car?""", True],
 ["""John had a car Eve bought. John had a car?""", True],
 ["""John had a car Eve liked. Eve had a car?""", None],
 ["""John had a car Eve bought. John bought a car?""", None],
 ["""John had a car Eve bought. John had a car which Eve bought?""", True],
 ["""John had a red car Eve bought. John had a car which Eve bought?""", True],
 ["""John had a red car which Mike bought. John had a car Mike bought?""", True],
 ["""John had a red car Eve bought. John had a black car which Eve bought?""", None],
 ["""John had a red car which Eve bought. John had a black car Eve bought?""", None],
 ["""John had a car Eve bought. John had a car which Eve did not buy?""", None],
 ["""John had a car which Mike did not buy. John had a car Mike did not buy?""", True],
 ["""John did not have a red car which Eve bought. John did not have a red car which Eve bought?""", True],
 ["""John drove a car which Eve bought. John drove a car which Eve bought?""", True],
 ["""John drove a car which Eve bought. John drove a car which Eve saw?""", None],
 ["""John drove a car which Eve bought. John drove a car which Mike bought?""", None],
 ["""John drove a car which Eve bought. John drove a car Eve bought?""", True],
 ["""John drove a car which Eve bought. John drove a car Eve saw?""", None],
 ["""John drove a car which Eve bought. John drove a car Mike bought?""", None],
 ["""John drove a car Mike bought. John drove a car Mike bought?""", True],
 ["""John drove a car Eve bought. John drove a car Mike bought?""", None],
 ["""John drove a car Eve bought. John drove a car Eve saw?""", None],
 ["""John drove a car Mike bought. John drove a car which Mike bought?""", True],
 ["""John drove a car Eve bought. John drove a car which Eve saw?""", None],
 ["""John drove a car Eve bought. John drove a car which Mike bought?""", None],
 ["""John drove a car Eve bought. Eve drove a car?""", None],
 ["""John drove a car Eve bought. John drove a car?""", True],
 ["""John drove a car Mike bought. John drove a car which Mike bought?""", True],
 ["""John drove a red car Mike bought. John drove a car which Mike bought?""", True],
 ["""John drove a red car which Eve bought. John drove a car Eve bought?""", True],
 ["""John drove a red car Eve bought. John drove a black car which Eve bought?""", None],
 ["""John drove a red car which Eve bought. John drove a black car Eve bought?""", None],
 ["""John drove a car Eve bought. John drove a car which Eve did not buy?""", None],
 ["""John drove a car which Mike did not buy. John drove a car Mike did not buy?""", True],
 ["""John did not have a red car which Eve bought. John did not have a red car which Eve bought?""", True],
 ["""John is a man whom Eve liked. John is a man whom Eve liked?""", True],
 ["""John is a man whom Eve liked. John is a man whom Eve saw?""", None],
 ["""John is a man whom Eve liked. John is a man whom Mike liked?""", None],
 ["""John is a man whom Eve liked. John is a man Eve liked?""", True],
 ["""John is a man whom Eve liked. John is a man Eve saw?""", None],
 ["""John is a man whom Eve liked. John is a man Mike liked?""", None],
 ["""John is a man Eve liked. John is a man Eve liked?""", True],
 ["""John is a man Eve liked. John is a man Mike liked?""", None],
 ["""John is a man Eve liked. John is a man Eve saw?""", None],
 ["""John is a man Eve liked. John is a man whom Eve liked?""", True],
 ["""John is a man Eve liked. John is a man whom Eve saw?""", None],
 ["""John is a man Eve liked. John is a man whom Mike liked?""", None],
 ["""John is a man Eve liked. John is a man whom Eve liked?""", True],
 ["""John is a man whom Eve liked. John is a man Eve liked?""", True],
 ["""John is a strong man Eve liked. John is a strong man whom Eve liked?""", True],
 ["""John is a strong man whom Eve liked. John is a strong man Eve liked?""", True],
 ["""John is a strong man Eve liked. John saw a strong man whom Eve liked?""", None],
 ["""John is a strong man whom Eve liked. John saw a strong man Eve liked?""", None],
 ["""John is a man Eve liked. John is a man whom Eve did not like?""", False],
 ["""John is a man whom Eve did not like. John is a man Eve did not like?""", True],
 ["""John is not a man whom Eve liked. John is not a man whom Eve liked?""", True],
 ["""John is a man Eve liked. John is a man?""", True],
 ["""John is a man Eve liked. Eve liked John?""", True],
 ["""John is a man Mary liked. Mary liked John?""", True],
 ["""John is a man Mary liked. Mary liked a man?""", True],
 ["""John is a man Mary liked. Mary liked the man?""", True],
 ["""A man had a car which a woman bought. A man had a car which a woman bought?""", True],
 ["""A man had a car a woman bought. A man had a car which a woman bought?""", True],
 ["""A man had a car which a woman bought. A man had a car which a woman liked?""", None],
 ["""A man had a car which a woman bought. A man had a car which a man bought?""", None],
 ["""A man had a car a woman bought. A man had a car which a woman bought?""", True],
 ["""A man had a car a woman bought. A woman bought a car?""", True],
 ["""A man had a car a woman bought. The woman bought a car?""", True],
 ["""A man had a car a woman bought. The woman did not buy a car?""", False],
 ["""A man had a car a woman bought. A man had a bike?""", None],
 ["""A man had a car a woman bought. A woman bought a red car?""", None],
 ["""A man had a car a woman bought. A man bought a car?""", None],
 ["""A man had a car a woman bought. The man did not have a car?""", False],
 ["""A man drove a car which a woman bought. A man drove a car which a woman bought?""", True],
 ["""A man drove a car a woman bought. A man drove a car which a woman bought?""", True],
 ["""A man drove a car which a woman bought. A man drove a car a woman bought?""", True],
 ["""A man drove a car which a woman bought. A man drove a car which a woman liked?""", None],
 ["""A man drove a car which a woman bought. A man drove a car?""", True],
 ["""A man drove a car which a woman bought. A man drove the car?""", True],
 ["""A man drove a car which a woman bought. A woman drove the car?""", None],
 ["""A man drove a car which a woman bought. A woman bought a car?""", True],
 ["""A man drove a car which a woman bought. A woman bought the car?""", True],
 ["""A man had a car which a woman bought. A man had a car?""", True],
 ["""A man had a car which a woman bought. A man had the car?""", True],
 ["""A man had a car which a woman bought. A woman had the car?""", None],
 ["""A man had a car which a woman bought. A woman bought a car?""", True],
 ["""A man had a car which a woman bought. A woman bought the car?""", True],
 ["""A man had a car which a woman bought. A man bought the car?""", None],
 ["""Cars are old. Cars are old?""", True],
 ["""A red car is big. A new car is small. A car is red?""", True],
 ["""A red car is big. A new car is small. A car is new?""", True],
 ["""A red car is big. A new car is small. A car is old?""", None],
 ["""A red car is big. A new car is nice. A car is red and big?""", True],
 ["""A red car is big. A new car is nice. A car is red and nice?""", None],
 ["""A red car is big. A new car is nice. The car is new?""", True],
 ["""A red car is big. A new car is nice. The car is red?""", None],
 ["""A red car is big. A new car is nice. The red car is big?""", True],
 ["""A red car is big. A new car is nice. The new car is nice?""", True],
 ["""A red car is big. The red car is strong. The car is red and strong?""", True],
 ["""A red car is big. The car is strong. The car is red and strong?""", True],
 ["""A red car is big. The car is strong. The car is black?""", None],
 ["""A red car is big. The car is strong. A car is black?""", None],
 ["""A man had a car which a woman bought. The car was red. A man had a car?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had the car?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had a red car?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had the bike?""", None],
 ["""A man had a car which a woman bought. The car was red. The man had a black car?""", None],
 ["""A man had a car which a woman bought. The car was red. The man had the red car?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had the car which a woman bought?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had the red car which a woman bought?""", True],
 ["""A man had a car which a woman bought. The car was red. The man had a car which a boy bought?""", None],
 ["""A man had a car which a woman bought. The car was red. A man had a red car which a woman bought?""", True],
 ["""A man had a car which a woman bought. The car was red. The man did not have the red car which a woman bought?""", False],
 ["""A man had a car which he bought. The car was red. The man bought the red car?""", True],
 ["""A man had a car which he bought. The car was red. A man bought a red car?""", True],
 ["""A man who ate breakfast had a car which a woman bought. The car was red.
     A man who ate breakfast had a red car which a woman bought?""", True],
 ["""A man who ate breakfast had a car.
     The man ate breakfast?""", True],
 ["""A man who ate breakfast had a car which a woman bought. The car was red. 
     The man who ate breakfast had the red car which the woman bought?""", True],
 ["""A man who ate breakfast had a car which a woman bought. The car was red.
     The man who ate breakfast had the red car which a woman bought?""", True],
 ["""A man liked a car. The man did not like the car?""", False],
 ["""A man liked a car which a woman bought. The car was red. A man liked a car?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked the car?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked a red car?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked the bike?""", None],
 ["""A man liked a car which a woman bought. The car was red. The man liked a black car?""", None],
 ["""A man liked a car which a woman bought. The car was red. The man liked the red car?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked the car which a woman bought?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked the red car which a woman bought?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man liked a car which a boy bought?""", None],
 ["""A man liked a car which a woman bought. The car was red. A man liked a red car which a woman bought?""", True],
 ["""A man liked a car which a woman bought. The car was red. The man did not like the red car which the woman bought?""", False],
 ["""A man liked a car which a woman bought. The car was red. The man did not like the red car which a woman bought?""", False],
 ["""A man liked a car which a woman bought. The car was red. A man did not like a red car which a woman bought?""", None],
 ["""A man liked a car which he bought. The car was red. The man bought the red car?""", True],
 ["""A man liked a car which he bought. The car was red. A man bought a red car?""", True],
 ["""A man who ate breakfast liked a car which a woman bought. The car was red.
     A man who ate breakfast liked a red car which a woman bought?""", True],
 ["""A man who ate breakfast liked a car.
     The man ate breakfast?""", True],
 ["""A man who ate breakfast liked a car which a woman bought. The car was red. 
     The man who ate breakfast liked the red car which the woman bought?""", True],
 ["""A man who ate breakfast liked a car which a woman bought. The car was red.
     The man who ate breakfast liked the red car which a woman bought?""", True],
 ["""A man did have a car. A man had a car?""", True],
 ["""A man had a car. A man did have a car?""", True],
 ["""The man has a car. The man does have a car?""", True],
 ["""A man had a car. A man has a car?""", True],
 ["""A man had a car. The man has a car?""", True],
 ["""The elephants saw a fox. They were nice. The elephants were nice?""", True],
 ["""The elephants saw a fox. They were nice. The fox was nice?""", None],
 ["""The elephants saw a fox. It was nice.  The fox was nice?""", True],
 ["""The elephants saw a fox. It was nice.  The elephants were nice?""", None],
 ["""The fox saw the elephants. They were nice. The elephants were nice?""", True],
 ["""The fox saw the elephants. They were nice. The fox was nice?""", None],
 ["""The fox saw the elephants. It was nice.  The fox was nice?""", True],
 ["""The fox saw the elephants. It was nice.  The elephants were nice?""", None],
 ["""A gray elephant was nice. A white elephant was nice. The elephant was cool. The white elephant was cool?""", True],
 ["""A gray elephant was nice. A white elephant was nice. The elephant was cool. The gray elephant was cool?""", None],
 ["""A gray elephant was nice. A white elephant was nice. It was cool. The white elephant was cool?""", True],
 ["""A gray elephant was nice. A white elephant was nice. It was cool. The gray elephant was cool?""", None],
 ["""A big old grey elephant was strong. The big animal lifted a stone. The stone was red. The old animal lifted a red stone?""", True, ['nochange']],
 ["""A big old grey elephant was strong. The big animal lifted a stone. The stone was heavy. The old animal lifted a heavy stone?""", True, ['nochange']],
 ["""Mary was in a room. She was in the room?""", True, ['nochange']],
 ["""Mary was in a room. She was in a room?""", True, ['nochange']],
 ["""Mary was in a room. She was not in the room?""", False, ['nochange']],
 ["""Mary was in a room. She was not in a room?""", False, ['nochange']],
 ["""She was in a room. She was in the room?""", True, ['nochange']],
 ["""An apple was bad. She was in a room. She was in the room?""", True, ['nochange']],
 ["""An apple was bad and she was in a room. She was in the room?""", True, ['nochange']],
 ["""An apple was bad. She was in a room. An apple was in a room?""", None, ['nochange']],
 ["""An apple was bad and she was in a room. An apple was in a room?""", None, ['nochange']],
 ["""John was bad. She was in a room. John was in a room?""", None, ['nochange']],
 ["""John has three cars. John has three cars?""", True],
 ["""If John has three cars, John has three cars?""", True],
 ["""John has three cars. John has two cars?""", False],
 ["""If John has three cars, John has two cars?""", None],
 ["""John has three nice cars. John has three nice cars?""", True],
 ["""Animals have two legs. Animals have two legs?""", True],
 ["""Animals have two legs. Animals have three legs?""", False],
 ["""Animals have two nice legs. Animals have two nice legs?""", True],
 ["""Animals have two nice legs. Animals have two long legs?""", None],
 ["""An animal had two legs. The animal had two legs?""", True],
 ["""An animal had two legs. The animal had three legs?""", False],
 ["""An animal had two nice legs. The animal had two nice legs?""", True],
 ["""An animal had two nice legs. The animal had two long legs?""", None],
 ["""If John has three cars, John has three cars?""", True],
 ["""John has three cars. John has two cars?""", False],
 ["""If John has three cars, John has two cars?""", None],
 ["""John has three nice cars. John has three nice cars?""", True],
 ["""John has three cars which are nice. John has three nice cars?""", True],
 ["""John has three nice cars. John has three cars?""", None],
 ["""John has three nice cars. John has three red cars?""", None],
 ["""John has three nice big cars. John has three nice big cars?""", True],
 ["""John has three nice big cars. John has three big nice cars?""", True],
 ["""John has three nice cars. John has two cars?""", False],
 ["""John has three big nice cars. John has two nice cars?""", False],
 ["""John has three big nice cars. John has two big cars?""", False],
 ["""If John has three big nice cars, he is rich. John has three nice big cars. John is rich?""", True],
 ["""If John has three big nice cars, he is rich. John has three nice cars. John is rich?""", None],
 ["""If a person has three big nice cars, he is rich. John has three nice big cars. John is rich?""", True],
 ["""John has three nice cars. John has a car?""", True],
 ["""John has three nice cars. John has a nice car?""", True],
 ["""An animal had two legs. The animal had legs?""", True],
 ["""An animal had two legs. The animal had a leg?""", True],
 ["""An animal had two strong legs. The animal had a strong leg?""", True],
 ["""John has cars. John has cars?""", True],
 ["""John has blue cars. John has a car?""", True],
 ["""John has blue cars. John has a blue car?""", True],
 ["""John has blue cars. John has one car?""", None],
 ["""John has one car. John has cars?""", True],
 ["""Animals have legs. Animal has a leg?""", True],
 ["""Animals have legs. Animal has one leg?""", None],
 ["""Penguins live in the water. Penguins live in the water?""", True],
 ["""Penguins live in the water. Penguins live in water?""", True],
 ["""Penguins live in the water. Penguins live?""", True],
 ["""Penguins live in the water. Penguins live in stone?""", None],
 ["""Penguins live in the water. Penguins live in the stone?""", None],
 ["""Penguins live in water. Penguins live in water?""", True],
 ["""Penguins live in water. Penguins live in stone?""", None],
 ["""Penguins live in water. Penguins live in the stone?""", None],
 ["""Penguins happily live in water. Penguins happily live in water?""", True],
 ["""Penguins happily live in water. Penguins live?""", True],
 ["""Penguins happily live in water. Penguins badly live in water?""", None],
 ["""Penguins happily live in cold water. Penguins happily live in cold water?""", True],
 ["""Penguins happily live in cold water. Penguins live in water?""", True],
 ["""Penguins happily live in cold water. Penguins live in cold water?""", True],
 ["""Penguins happily live in cold water. Penguins live in hot water?""", None],
 ["""The head of Mary is clean. The head of Mary is clean?""", True],
 ["""The head of Mary is clean. A head of Mary is clean?""", True],
 ["""The head of Mary is clean. A head of Mike is clean?""", None],
 ["""The head of Mary is clean. The head is clean?""", True],
 ["""The head of Mary is clean. Mary has a clean head?""", True],
 ["""The car of Mary is clean. Mary has a car?""", True],
 ["""The car of Mary is clean. Mike has a car?""", None],
 ["""The car of Mary is clean. The car of Mike is clean?""", None],
 ["""The car of Mary is clean. Mary has a clean car?""", True],
 ["""The car of Mary is clean. Mary has a red car?""", None],
 ["""The car of Mary is clean. Mary has a clean bike?""", None],
 ["""A leg of Mary is clean. A leg of Mary is clean?""", True],
 ["""A leg of Mary is clean. A leg of Mary is long?""", None],
 ["""A leg of Mary is clean. A leg of Mike is clean?""", None],
 ["""Mary's head is clean. Mary's head is clean?""", True],
 ["""Mary's head is clean. A head of Mary is clean?""", True],
 ["""Mary's head is clean. A head of Mike is clean?""", None],
 ["""Mary's head is clean. The head is clean?""", True],
 ["""Mary's leg is clean. A leg of Mary is clean?""", True],
 ["""Mary's leg is clean. A leg of Mary is long?""", None],
 ["""Mary's leg is clean. A leg of Mike is clean?""", None],
 ["""Mary's car is clean. Mary has a car?""", True],
 ["""Mary's car is clean. Mary has a clean car?""", True],
 ["""Mary's car is clean. Mary has a red car?""", None],
 ["""Mary's car is clean. Mary has a clean bike?""", None],
 ["""Elephant's head is green. John is an elephant. John has a head. John has a green head?""", True],
 ["""Big elephant's head is green. John is a big elephant. John has a head. John has a green head?""", True],
 ["""Big elephant's head is green. John is an elephant. John has a head. John has a green head?""", None],
 ["""A head of an elephant is green. All elephants have a head. An elephant has a green head?""", True],
 ["""A head of an elephant is green. Elephants have a head. An elephant has a green head?""", True],
 ["""A head of an elephant is green. Elephants have a head. John is an elephant. John has a green head?""", True],
 ["""John saw the head of Mary. John saw the head of Mary?""", True],
 ["""John saw the head of Mary. John saw a head of Mary?""", True],
 ["""John saw the head of Mary. John saw the head of Mike?""", None],
 ["""John saw the head of Mary. John saw a head?""", True],
 ["""John saw the head of Mary. John saw the hands of Mary?""", None],
 ["""John saw the car of Mary. Mary had a car?""", True],
 ["""John saw the head of the elephant. John saw the head of the elephant?""", True],
 ["""John saw the head of the elephant. John saw the head?""", True],
 ["""John saw the head of the elephant. John saw a head?""", True],
 ["""John saw the head of the elephant. John saw the tail of the elephant?""", None],
 ["""John saw the head of the elephant. John saw a nice head?""", None],
 ["""John saw a head of an elephant. John saw a head of an elephant?""", True],
 ["""John saw a head of an elephant. John saw the head of the elephant?""", None],
 ["""John saw a head of an elephant. John saw the head?""", True],
 ["""John saw a head of an elephant. John saw a head?""", True],
 ["""John saw a head of an elephant. John saw the tail of the elephant?""", None],
 ["""John saw a head of an elephant. John saw a tail of an elephant?""", None],
 ["""John saw a head of an elephant. John saw a nice head?""", None],
 ["""John saw Mary's head. John saw Mary's head?""", True],
 ["""John saw Mary's head. John saw a head of Mary?""", True],
 ["""John saw Mary's head. John saw Mike's head?""", None],
 ["""John saw Mary's head. John saw a head of Mary?""", True],
 ["""John saw Mary's head. John saw the head of Mike?""", None],
 ["""John saw Mary's head. John saw a head?""", True],
 ["""John saw Mary's head. John saw the hands of Mary?""", None],
 ["""John saw Mary's car. Mary had a car?""", True],
 ["""John saw Mary's clean car. Mary had a clean car?""", True],
 ["""John saw Mary's clean car. Mary had a red car?""", None],
 ["""John saw Mary's clean car. Mary had a clean bike?""", None],
 ["""John saw elephant's head. John saw elephant's head?""", True],
 ["""John saw elephant's head. John saw the head?""", True],
 ["""John saw elephant's head. John saw a head of an elephant?""", True],
 ["""John saw elephant's head. John saw a head of a tiger?""", None],
 ["""John saw elephant's head. John saw a head?""", True],
 ["""John saw elephant's head. John saw the tail of the elephant?""", None],
 ["""John saw elephant's head. John saw a nice head?""", None],
 ["""John saw a head of an elephant. John saw a head of the elephant?""", True],
 ["""John saw a head of an elephant. John saw a head of an elephant?""", True],
 ["""John saw a head of the elephant. John saw a head of the elephant?""", True],
 ["""John saw a head of the elephant. John saw a head of an elephant?""", True],
 ["""John saw a head of an elephant. John saw a head of the bear?""", None],
 ["""John saw a head of an elephant. John saw a head of a bear?""", None],
 ["""John saw a head of the elephant. John saw a head of the bear?""", None],
 ["""John saw a head of the elephant. John saw a head of a bear?""", None],
 ["""John saw a head of an elephant. John saw a tail of the elephant?""", None],
 ["""John saw a head of an elephant. John saw a tail of an elephant?""", None],
 ["""John saw a head of the elephant. John saw a tail of the elephant?""", None],
 ["""John saw a head of the elephant. John saw a tail of an elephant?""", None],
 ["""John saw a twig of an elephant. The elephant had a twig?""", True],
 ["""John saw a twig of an elephant. The elephant had a spoon?""", None],
 ["""John saw a twig of an elephant. An elephant had a twig?""", True],
 ["""John saw a twig of an elephant. An elephant had a spoon?""", None],
 ["""John saw the twig of an elephant. The elephant had a twig?""", True],
 ["""John saw the twig of an elephant. The elephant had the twig?""", True],
 ["""John saw the twig of an elephant. The elephant had a spoon?""", None],
 ["""John saw a blue head of a red elephant. John saw a blue head of a red elephant?""", True],
 ["""John saw the blue head of the red elephant. John saw the blue head of the red elephant?""", True],
 ["""John saw the blue head of the red elephant. John saw the red head of the red elephant?""", None],
 ["""John saw the blue head of the red elephant. John saw the red head of the blue elephant?""", None],
 ["""John saw a blue head of a red elephant. John saw a blue head?""", True],
 ["""John saw a blue head of a red elephant. John saw the blue head?""", True],
 ["""John saw a blue head of a red elephant. John saw the head?""", True],
 ["""John saw a blue head of a red elephant. John saw a red head?""", None],
 ["""John saw a blue head of a red elephant. John saw a blue tail?""", None],
 ["""John saw a blue head of a red elephant. John saw the blue head?""", True],
 ["""John saw a blue head of a red elephant. John saw a head of an elephant?""", True],
 ["""John saw a blue head of a red elephant. John saw a head of the red elephant?""", True],
 ["""The hand of a man moved a wheel. The hand of a man moved a wheel?""", True],
 ["""The hand of a man moved a wheel. The man had a hand?""", True],
 ["""The hand of a man moved a wheel. A man had a hand?""", True],
 ["""The hand of a man moved a wheel. A man had a wheel?""", None],
 ["""The hand of a man moved a wheel. A man was a wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand of a man moved a wheel of a large wheelbarrow?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand of an elephant moved a wheel of a large wheelbarrow?""", None],
 ["""The blue hand of a man moved a wheel of the large wheelbarrow. A blue hand of a man moved a wheel of a large wheelbarrow?""", True],
 ["""The blue hand of a man moved the wheel of the large wheelbarrow. The blue hand of a man moved the wheel of the large wheelbarrow?""", True],
 ["""The blue hand of a man moved the wheel of the large wheelbarrow. The blue hand of a man moved the large wheelbarrow?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A hand moved a wheel?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A hand moved a wheelbarrow?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A blue hand moved a wheel?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A right hand moved a wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A leg moved a wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A hand moved a wheel of a small wheelbarrow?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a hand?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a blue hand?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a red hand?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The wheelbarrow had a wheel?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A large wheelbarrow had the wheel?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. A small wheelbarrow had the wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The large wheelbarrow had a wheel?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The small wheelbarrow had a wheel?""", None],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The wheelbarrow had a hand?""", None],
 ["""The blue hand of a man moved the wheel of the large wheelbarrow. Mary is a man?""", None, [{'mary': 'a tall object'}]],
 ["""The blue hand of a man moved a wheel of the large wheelbarrow. Mary is a man?""", None, [{'mary': 'a tall object'}]],
 ["""The hand of a man is nice. Mary is a man?""", None, [{'mary': 'a tall object'}]],
 ["""A hand of a man moved a wheel. Mary is a man?""", None, [{'mary': 'a tall object'}]],
 ["""The hand of a man moved a wheel. Mary is a man?""", None, [{'mary': 'a tall object'}]],
 ["""John ate berries with the edge of a spoon. John ate berries with the edge of a spoon?""", True],
 ["""John ate berries with an edge of a spoon. John ate berries with an edge of a spoon?""", True],
 ["""John ate berries with the edge of a spoon. John ate berries with the edge of a fork?""", None],
 ["""John ate berries with the edge of a spoon. John ate berries with the tip of a spoon?""", None],
 ["""John ate berries with an edge of a spoon. John ate berries with an edge?""", True],
 ["""John ate berries with an edge of a spoon. John ate berries with a tip?""", None],
 ["""John ate berries with an edge of a spoon. A spoon had an edge?""", True],
 ["""John ate berries with an edge of a spoon. The spoon had the edge?""", True],
 ["""John ate berries with the edge of the spoon. The spoon had the edge?""", True],
 ["""John ate berries with the edge of the spoon. The spoon had the tip?""", None],
 ["""John ate berries with the edge of a spoon. John is a spoon?""", None],
 ["""John ate berries with the edge of a spoon. John is an edge?""", None],
 ["""John ate berries with the edge of a spoon. Berries have an edge?""", None, [{'berries': 'big objects'}]],
 ["""Bears eat berries in a forest. Bears eat berries in a forest?""", True],
 ["""Bears eat berries in a forest. Bears eat berries in a big forest?""", None],
 ["""Bears eat berries in a forest. Bears eat berries in a field?""", None],
 ["""Bears do not eat berries in a forest. Bears eat berries in a forest?""", False],
 ["""Bears ate berries in a forest. Bears did not eat berries in a forest?""", False],
 ["""Bears ate berries in a forest. Bears did not eat berries in a field?""", None],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest which was bought by her?""", True],
 ["""Bears ate nice berries in a big forest which was seen by Mary. Bears ate berries in the forest which was seen by her?""", True],
 ["""Bears ate nice berries in a big forest which was bought by Mike. Bears ate berries in the forest which was bought by him?""", True],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest which was bought by a man?""", None],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. The forest was bought by Mary?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in a forest which was seen by Mary. Bears ate berries in the forest seen by Mary?""", True],
 ["""Bears ate berries in a forest which was bought by Mike. Bears ate berries in the forest bought by Mike?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was seen by Mary. Mary saw the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was bought by Mike. Mike bought the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears drank?""", None],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate berries?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate honey?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a forest with a spoon?""", True],
 ["""John ate berries in a forest with a spoon. John ate berries in a field?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a nice forest with a spoon?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a nice forest?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries with a spoon in a nice forest?""", None],
 ["""John ate berries with the help of a spoon. John ate berries with the help of a spoon?""", True],
 ["""John ate berries with the help of a spoon. John ate berries with the help of a spade?""", None],
 ["""John lives in a car which is red. The car is red?""", True],
 ["""John lives in a car which is red. The car is nice?""", None],
 ["""John lives in a car which is red. John lives in a red car?""", True],
 ["""John lives in a car which is red. John lives in a nice car?""", None],
 ["""John lives in a car which is red and was bought by Mary. The nice car was bought by Mary?""", None],
 ["""John lives in a car which is red and was bought by Mary. The car was bought by John?""", None],
 ["""John has a car which is nice and red. The car is red and nice?""", True],
 ["""John has a car which is nice and red. The red car is nice?""", True],
 ["""John has a car which is nice and red. The big car is nice?""", None],
 ["""John has a red car which is nice and big. The nice car is big and red?""", True],
 ["""John has a red car which is nice and big. The car is good?""", None],
 ["""John lives in a nice car which was red and was bought by Mary. John lives in a nice yellow car?""", None],
 ["""John lives in a nice car which was red and was bought by Mike. John lives in a car which was bought by Mike?""", True],
 ["""John lives in a car which is red and was bought by Mary. The car was bought by John?""", None],
 ["""John lives in a red car bought by Mary. Mary bought the car?""", True],
 ["""John lives in a red car bought by Mary. Mary bought the car where John lives?""", True],
 ["""John lives in a red car bought by Mary. Mary bought the car where John ate?""", None],
 ["""John lives in a red car bought by Mary. Mary bought the car where Mike lives?""", None],
 ["""John shot an elephant in his pyjamas. The elephant was in his pyjamas?""", None],
 ["""John shot an elephant in his pyjamas. John shot in his pyjamas?""", True],
 ["""Mike ate berries in the forest bought by Mary. Mike ate berries in the forest bought by Mary?""", True],
 ["""Mike ate berries in the forest bought by Mary. Mike ate berries in the forest bought by John?""", None],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest which was bought by Mary?""", True],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest which was bought by John?""", None],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest bought by Mary?""", True],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in the forest bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in the forest bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest which was bought by Mary?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest which was bought by John?""", None],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Cars are nice. Cars have brakes. Cars are nice and have brakes?""", True],
 ["""Cars are nice. Cars are nice and have brakes?""", None],
 ["""Cars have brakes. Cars are nice and have brakes?""", None],
 ["""Cars are nice and cool and have brakes. Cars are nice and cool and have brakes?""", True],
 ["""Cars are nice and cool and have brakes. Cars have brakes and are nice and cool?""", True],
 ["""Cars are cool and have brakes. Cars are nice and cool and have brakes?""", None],
 ["""Cars are nice and cool. Cars have brakes and are nice and cool?""", None],
 ["""Cars have fenders. Cars have brakes. Cars have brakes and fenders?""", True],
 ["""Cars have fenders. Cars have brakes and fenders?""", None],
 ["""Cars have brakes. Cars have brakes and fenders?""", None],
 ["""John is defeated. John defeated?""", None],
 ["""John is defeated. Mike is defeated?""", None],
 ["""John is defeated. John is defeated?""", True],
 ["""John is defeated. John is not defeated?""", False],
 ["""If an animal is cool and defeated then it is green. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. John is green?""", True],
 ["""If an animal is cool and defeated then it is green. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. John is not green?""", False],
 ["""If an animal is cool and defeated then it is green. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. Mike is green?""", None],
 ["""If an animal is cool and defeated then it is green. 
   John is a cool defeated animal. 
   Mike is an animal. Mike is cool. John is green?""", True],
 ["""If an animal is cool and defeated then it is green. 
   John is a cool defeated animal. 
   Mike is an animal. Mike is cool. John is not green?""", False],
 ["""If an animal is cool and defeated then it is green. 
   John is a defeated animal. 
   Mike is an animal. Mike is cool. John is green?""", None],
 ["""If someone is a bird and wounded then they are abnormal. John is wounded. John is a bird. John is abnormal?""", True],
 ["""If someone is a bird and wounded then they are abnormal. John is a bird. John is abnormal?""", None],
 ["""John was nice and defeated. John was nice and defeated?""", True],
 ["""John was nice and defeated. John was nice?""", True],
 ["""John was defeated. John was defeated?""", True],
 ["""John is defeated. John was defeated?""", None],
 ["""John was defeated. John is defeated?""", None],
 ["""John is defeated. John is defeated?""", True],
 ["""If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals. 
    John is badly defeated. John is weak?""", True],
 ["""If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals. 
    John is badly defeated. Mike is weak?""", None],
 ["""If someone is a nice animal and badly defeated then they are weak. John is a nice animal. 
    Mike is badly defeated. Mike is weak?""", None],
 ["""Muggles cannot disappear. Mr Dursley is a Muggle. Mr Dursley can disappear?""", False],
 ["""Muggles can not disappear. Mr Dursley is a Muggle. Mr Dursley can disappear?""", False],
 ["""Americans cannot disappear. Mr Dursley is an American. Mr Dursley can disappear?""", False],
 ["""Americans can not disappear. Mr Dursley is an American. Mr Dursley can disappear?""", False],
 ["""Catholics can not disappear. Mr Dursley is a catholic. Mr Dursley can disappear?""", False],
 ["""Clinton defeated Dole. Clinton defeated Dole?""", True],
 ["""Clinton defeated Dole. Clinton defeated Mike?""", None],
 ["""Dole was defeated by Clinton. Dole was defeated by Clinton?""", True],
 ["""Dole was defeated by Clinton. Dole was defeated by Mike?""", None],
 ["""Clinton defeated Dole. Dole was defeated by Clinton?""", True],
 ["""Clinton defeated Dole. Dole was defeated by Mike?""", None],
 ["""Dole was defeated by Clinton. Clinton defeated Dole?""", True],
 ["""Dole was defeated by Clinton. Mike defeated Dole?""", None],
 ["""The car is red. The car is red?""", True],
 ["""The car is red. The car is nice?""", None],
 ["""Sue is a true patriot. Sue is a true patriot?""", True],
 ["""Sue is a true patriot. Sue is a nice patriot?""", None],
 ["""Sue is a true patriot. Sue is a true driver?""", None],
 ["""We are in the barn. We are in the barn?""", True],
 ["""We are in the barn. We are in the shop?""", None],
 ["""We are in the barn. We are on the barn?""", None],
 ["""Agatha is in trouble. Agatha is in trouble?""", True],
 ["""Agatha is in trouble. Agatha is in the barn?""", None],
 ["""Agatha is in trouble. Agatha is through trouble?""", None],
 ["""There is a ghost in the room. There is a ghost in the room?""", True],
 ["""There is a ghost in the room. A ghost is in the room?""", True],
 ["""There is a ghost in the room. There is a lamp in the room?""", None],
 ["""There is a ghost in the room. There is a ghost in the barn?""", None],
 ["""These links present the many viewpoints that existed. These links present the lemmas that existed?""", None],
 ["""John is nice. Is it true that John is nice?""", True],
 ["""John is nice. Is it false that John is nice?""", False],
 ["""John is nice. It is true that John is nice?""", True],
 ["""John is nice. Is it false that John is nice?""", False],
 ["""John smokes tobacco with a probability 10 percent. Does John smoke?""", None],
 ["""Ellen is fond of John. Ellen is afraid of who?""", None],
 ["""John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear. 
      Which man has a potato?""", None],
 ["""John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear. 
      Which bad man has a pear?""", None],
 ["""John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear. 
      Which nice man has an apple and a pear?""", None],
 ["""Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals. 
      Which table can fly?""", None],
 ["""John is in the box at the red house. A box is at a house?""", True],
 ["""John is in the box at a red house. The box is at a house?""", True],
 ["""John is in the box at a red house. The red box is at a house?""", None],
 ["""John is in the box at a red house. The box is at a blue house?""", None],
 ["""John is in a box at the red house. A box is at a house?""", True],
 ["""John is in a box at the red house. A box is at a house?""", True],
 ["""John is in a box at the red house. The box is at a house?""", True],
 ["""John is in a box at the red house. A box is at the red house?""", True],
 ["""During 1800, John jumped in a house. During 1800, John jumped?""", True],
 ["""During 1800, John jumped in a house. During 1801, John jumped?""", None],
 ["""Nile's length is 80 kilometers. The length of Nile is 80 kilometers?""", True],
 ["""Nile's length is 80 kilometers. The length of Nile is 90 kilometers?""", False],
 ["""Car's length is 80 kilometers. The length of the car is 80 kilometers?""", True],
 ["""Car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""The car's length is 80 kilometers. The length of the car is 80 kilometers?""", True],
 ["""The car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""The red car's length is 80 kilometers. The length of the blue car is 80 kilometers?""", None],
 ["""The red car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""Emajogi's length is 80 kilometers. Emajogi's length is 80 kilometers?""", True],
 ["""Emajogi's length is 80 kilometers. Emajogi's length is 90 kilometers?""", False],
 ["""Emajogi's length is 80 kilometers. The length of Emajogi is 80 kilometers?""", True],
 ["""Emajogi's length is 80 kilometers. The length of Emajogi is 90 kilometers?""", False],
 ["""The length of Emajogi is 80 kilometers. Emajogi is 80 kilometers long?""", True],
 ["""The length of Emajogi is 80 kilometers. Emajogi is 90 kilometers long?""", False],
 ["""The nice Emajogi is 80 kilometers long. The nice Emajogi is 80 kilometers long?""", True],
 ["""The nice Emajogi is 80 kilometers long. The nice Emajogi is 90 kilometers long?""", False],
 ["""The red straw is 10 meters long. The red straw is 10 meters long?""", True],
 ["""The red straw is 10 meters long. The red straw is 20 meters long?""", False],
 ["""John has the length 2 meters. John is 2 meters long?""", True],
 ["""John has the length 2 meters. John is 3 meters long?""", False],
 ["""John has length of 2 meters. John is 2 meters long?""", True],
 ["""John has length of 2 meters. John is 3 meters long?""", False],
 ["""John's length is 2 meters. John is 2 meters long?""", True],
 ["""The price of the red car is 2 dollars. The price of the red car is 2 dollars?""", True],
 ["""The price of the red car is 2 dollars. The price of the red car is 3 dollars?""", False],
 ["""The price of the red car is 2 dollars. The price of the red car is 2 euros?""", None],
 ["""The red car costs 2 dollars. The price of the red car is 2 dollars?""", True],
 ["""The red car costs 2 dollars. The price of the red car is 3 dollars?""", False],
 ["""The red car has a price of two dollars. The red car costs two dollars?""", True],
 ["""The red car has the price two dollars. The red car costs two dollars?""", True],
 ["""The red car has the price two dollars. The red car costs three dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The red car costs 3 dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The blue car costs 2 dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The car costs three dollars?""", True],
 ["""The red car has the price two dollars. The blue car costs three dollars. The price of the red car equals the price of the blue car?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The price of the red car equals the price of the red car?""", True],
 ["""The red car has the price three dollars. The blue car costs three dollars. The price of the red car is the same as the price of the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The price of the red car is the same as the price of the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car costs as much as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car costs as much as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car is as expensive as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car is as expensive as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car is as cheap as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car is as cheap as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car has the same price as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car has the same price as the blue car?""", False],
 ["""The length of the red car is three meters. The blue car is 2 meters long. The red car has the same length as the blue car?""", False],
 ["""The length of the red car is three meters. The blue car is 2 meters long. The red car does not have the same length as the blue car?""", True],
 ["""The length of the red car is three meters. The blue car is 3 meters long. The red car has the same length as the blue car?""", True],
 ["""The length of the red car is three meters. The blue car is 3 meters long. The red car does not have the same length as the blue car?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is more than the length of the black car?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is less than the length of the black car?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is less than 2 meters?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is over 2 meters?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters.   
      The length of the red car is more than 2 meters?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters.   
      The length of the red car is under 4 meters?""", True],
 ["""The length of the car is 3 meters. The bike has the same length as the car. The length of the bike is 3 meters?""", True],
 ["""The price of the car is 3 dollars. The bike has the same price as the car.  The price of the bike is 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 2 dollars?""", False],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 3 drahms?""", None],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The price of the bike is less than 20 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The price of the bike is more than 20 dollars?""", False],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs less than 20 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs more than 20 dollars?""", False],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs less than 20 tons?""", True],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs more than 2 tons?""", True],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs more than 20 tons?""", False],
 ["""The price of the car is below 20 dollars. The car costs less than 20 dollars?""", True],
 ["""The weight of the car is below 20 tons. The car weighs less than 20 tons?""", True],
 ["""The price of the car is above 20 dollars. The car costs more than 20 dollars?""", True],
 ["""The weight of the car is above 20 tons. The car weighs more than 20 tons?""", True]
]
