# 100-case representative subset of tests/tests_core.py  (generated 2026-05-29)
# 12 cases per phase (16 for Phase IV). Type totals across all 100: 25 True / 25 False / 25 Unknown(None) / 25 concrete.
# Per-phase (True/False/None/concrete): I 4/3/3/2  II 3/3/3/3  III 3/4/3/2  IV 4/4/4/4  V 4/3/2/3  VI 3/4/2/3  VII 1/1/5/5  VIII 3/3/3/3.
# Cases spread across subsections and spaced to avoid near-neighbours.
[

# === PHASE I: FOUNDATIONS  (T4 F3 N3 C2) ===
  ['Elephants are animals. John is an elephant. John is an animal?', True],
  ['John is a tall man or not a tall man?', True],
  ['A very big mouse is nice. The mouse is a very big mouse?', True],
  ['Elephants have trunks or tails. John is an elephant. John has no trunk. John has a tail?', True],
  ['Elephants are not birds. John is an elephant. John is a bird?', False],
  ['John is a tall man and not a tall man?', False],
  ['John is somewhat big. John is not big?', False],
  ['Elephants are big animals. John is an elephant. Who is nice?', None],
  ['John is in Estonia?', None],
  ['A not very big bear is nice. The bear is a somewhat big bear?', None],
  ['Elephants are animals. Who is an animal?', 'An elephant.'],
  ['Yellow and green elephants are nice. John is an elephant. John is yellow and green. John is nice?', 'Probably true.'],

# === PHASE II: REFERENCE & POSSESSION  (T3 F3 N3 C3) ===
  ['An apple was bad. She was in a room. She was in the room?', True],
  [' Elephants have long not red trunks. John is an elephant. John has a not red trunk?', True],
  ["The roof of John's house is green. John has a house?", True],
  ['Americans can not disappear. Mr Dursley is an American. Mr Dursley can disappear?', False],
  ['Elephants have no long red trunks. John is an elephant. John has a long red trunk?', False],
  ['The bicycle of Tom was new. Was the bicycle old?', False],
  ['An apple was bad. She was in a room. An apple was in a room?', None],
  ['Elephants have a trunk. Birds have a trunk?', None],
  ["John's brother has a car. John's sister has a car?", None],
  ['A boy saw a girl. He was nice. Who was nice?', ['The boy', 'The nice boy']],
  ['Elephants have long grey trunks. John is an elephant. Who has a grey trunk?', 'John.'],
  ["Mary's uncle arrived. Who has an uncle?", 'Mary.'],

# === PHASE III: QUANTIFIERS & COMPARISON  (T3 F4 N3 C2) ===
  ['John likes all boxers. Mike is a boxer. John likes Mike?', True],
  ['The red square has a nail. A blue square has a hole. A blue square has a hole?', True],
  ["John is as tall as Bill. Is John's height equal to Bill's?", True],
  ['All elephants are animals. Elephants are not animals?', False],
  ['Elephants are animals. All elephants are not animals?', False],
  ['The red car is faster than the blue car. Is the blue car faster than the red car?', False],
  ["This book is more interesting than that one. Is 'that one' more interesting?", False],
  ['Some elephants are animals. Some elephants are not animals?', None],
  ['The red square has a nail. A blue square has a hole. A red square has a hole?', None],
  ['The red car is faster than the blue car. Is the green car faster than the red car?', None],
  ['Bears eat most boxers. Mike is a boxer. Greg is a bear. Bears eats Mike?', 'Probably true.'],
  ['Most bears are big. John is a bear. John is big?', 'Likely true.'],

# === PHASE IV: MODIFICATION & STRUCTURE  (T4 F4 N4 C4) ===
  ['Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is not a bird?', True],
  ['John bought a red car and a blue bicycle. The bicycle was blue?', True],
  ['The tree growing near the river was tall. The tree grew near the river?', True],
  ['John has a car which is nice and red. The red car is nice?', True],
  ['Elephants, foxes and rabbits are neither birds nor small fish. John is a rabbit. John is a small fish?', False],
  ['The students studied hard and passed the exam. Did the students fail the exam?', False],
  ['The woman holding a heavy lamp sang. The lamp was light?', False],
  ['The student who passed the test studied a lot. Did the student fail the test?', False],
  ['Elephants are animals. Birds are not animals?', None],
  ['A tall and quiet man entered. A woman entered?', None],
  ['The child wearing a hat ran. The child wore a coat?', None],
  ['John had a car which Eve bought. John had a car Mike bought?', None],
  ['John bought a red car and a blue bicycle. What did John buy?', 'A red car and a blue bicycle'],
  ['Anna, the manager, called Eve. Who is the manager?', 'Anna.'],
  ['Bears who are nice eat fish who are strong. John is a nice bear. Bears who are nice eat fish who are strong?', [True, 'Likely true']],
  ['John works at the hospital every day. Where does John work?', 'At the hospital.'],

# === PHASE V: CLAUSE ALTERNATIONS  (T4 F3 N2 C3) ===
  ['The letter was written by Eve. Eve wrote the letter?', True],
  ['The bill was paid by John. Did John pay the bill?', True],
  ['Although John was tired, he finished the work. John finished the work?', True],
  ['John bought a book, and Bill said Peter did too. Did Bill say Peter bought a book?', True],
  ['John is defeated. John is not defeated?', False],
  ['The city was destroyed. Is the city intact?', False],
  ['Though Mary was ill, she traveled. Mary did not travel?', False],
  ['The house was built by Tom. Tom destroyed the house?', None],
  ['Mary opened the window to let in air. Air came in?', None],
  ['Mary was given a promotion. Who received a promotion?', 'Mary.'],
  ['A surgeon, Dr. Smith, entered the room. Who entered the room?', ['Dr. Smith.', 'A surgeon.']],
  ['John went to Paris and Mary to London. Where did Mary go?', ['London.', 'To London.']],

# === PHASE VI: EVENTS & STATE  (T3 F4 N2 C3) ===
  ['Bears quickly eat berries in a deep forest. John is a bear. John quickly eats berries in a deep forest?', True],
  ['The teacher showed the students a map. The students saw a map?', True],
  ['While John was cooking, Mary read a book. Mary read a book?', True],
  ['Bears do not eat berries in a forest. Bears eat berries in a forest?', False],
  ['John has finished his homework. Is the homework unfinished?', False],
  ['John stopped smoking. Does John smoke now?', False],
  ['Tallinn is in Estonia. Estonia is not outside Europe. Earth contains Europe.\n       Estonia contains Tartu. Riga is not in Estonia. Riga is in Estonia?', False],
  ['If a bear eats berries in a forest, it is hungry. John is a brown bear.\n      John draws berries in a deep forest. Who is hungry?', None],
  ['Susan bought herself a new car. Did Tom buy a car?', None],
  ['If a bear eats, it is hungry. John is a brown bear.\n      John quickly eats berries in a deep forest. Who is hungry?', 'John.'],
  ['The chef cooked a meal for the guests. Who was the meal for?', 'The guests.'],
  ['The train leaves at noon. When does the train leave?', 'At noon.'],

# === PHASE VII: QUESTIONS  (T1 F1 N5 C5) ===
  ['John is nice. Is it true that John is nice?', True],
  ['John is nice. Is it false that John is nice?', False],
  ['John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which man has a potato?', None],
  ['Ellen is fond of John. Who is Ellen afraid of?', None],
  ['Ellen is fond of John. Ellen is afraid of who?', None],
  ['John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which bad man has a pear?', None],
  ['Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals.\n      Which table can fly?', None],
  ['Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals.\n      Which animal cannot fly?', 'A fox'],
  ['Ellen is afraid of John. Who is Ellen afraid of?', 'John'],
  ['John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which man has an apple?', 'John'],
  ['John is a nice man. John has an apple. Mike is a nice man. Greg is a bad man. Mike has a pear.\n      Which nice man has a pear?', 'Mike'],
  ['Squirrels can fly. Foxes cannot fly. Squirrels and foxes are animals.\n      Which can fly?', 'A squirrel'],

# === PHASE VIII: REASONING  (T3 F3 N3 C3) ===
  ['If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals.\n    John is badly defeated. John is weak?', True],
  ['Penguins are birds. Penguins do not fly. Birds fly. John is a penguin. John is a bird?', True],
  ['Birds fly and eat. Baby birds do not fly. John is a baby bird. Mike is a bird.\n    John does not fly?', True],
  ['If an animal is cool and defeated then it is green.\n   John is an animal. John is cool.\n   Mike is an animal. Mike is cool. John is defeated. John is not green?', False],
  ['Penguins are birds. Penguins do not fly. Birds fly. Penguins fly?', False],
  ['Penguins are birds. Penguins do not fly. Birds fly. John is a penguin. John flies?', False],
  ['If animal or bird is nice and simple, it is cute. John is cute?', None],
  ['John is an elephant with a probability 50 percent. John is an elephant?', None],
  ['If a bear eats red berries, it is big. John eats berries. John is a bear.\n     John is big?', None],
  ['If X1 is a father of Y1, Y1 is a child of X1.\n      If X1 is a father of Y1 and Y1 is a father of Z1, X1 is a grandfather of Z1.\n      John is a father of Mike and Mickey. Luke is a father of John.\n      If X1 is a grandfather of Y1, Y1 is a grandchild of X1.\n      If X1 is male and X1 is a grandchild of Y1, X1 is a grandson of Y1.\n      Mike or Mickey is not female. Any person is male or female.\n      Who is a grandson of Luke?', 'Mike or Mickey.'],
  ['Tallinn is hardly in Latvia. Tallinn is in Latvia?', 'Likely false.'],
  ['It is not probable that John is a child of Mike. John is a child of Mike?', 'Probably false.'],
]
