[
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a hand?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a blue hand?""", True],
 ["""A blue hand of a man moved a wheel of a large wheelbarrow. The man had a red hand?""", None],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. The man had a crenkil?""", None],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. The wheelbarrow had a crenkil?""", True],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. A large wheelbarrow had the crenkil?""", True],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. A small wheelbarrow had the crenkil?""", None],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. The large wheelbarrow had a crenkil?""", True],
 ["""A blue hand of a man moved a crenkil of a large wheelbarrow. The small wheelbarrow had a crenkil?""", None],
 ["""The blue hand of a crenkil moved the wheel of the large wheelbarrow. Mary is a crenkil?""", None, [{'mary': 'a tall object'}]],
 ["""The blue hand of a crenkil moved a wheel of the large wheelbarrow. Mary is a crenkil?""", None, [{'mary': 'a tall object'}]],
 ["""The hand of a crenkil is nice. Mary is a crenkil?""", None, [{'mary': 'a tall object'}]],
 ["""A hand of a crenkil moved a wheel. Mary is a crenkil?""", None, [{'mary': 'a tall object'}]],
 ["""The hand of a crenkil moved a wheel. Mary is a crenkil?""", None, [{'mary': 'a tall object'}]],
 ["""John ate berries with the edge of a crenkil. John ate berries with the edge of a crenkil?""", True],
 ["""John ate berries with an edge of a crenkil. John ate berries with an edge of a crenkil?""", True],
 ["""John ate berries with the edge of a crenkil. John ate berries with the edge of a fork?""", None],
 ["""John ate berries with the edge of a crenkil. John ate berries with the tip of a crenkil?""", None],
 ["""John ate berries with an edge of a crenkil. John ate berries with an edge?""", True],
 ["""John ate berries with an edge of a crenkil. John ate berries with a tip?""", None],
 ["""John ate berries with an edge of a crenkil. A crenkil had an edge?""", True],
 ["""John ate berries with an edge of a crenkil. The crenkil had the edge?""", True],
 ["""John ate berries with the edge of the crenkil. The crenkil had the edge?""", True],
 ["""John ate berries with the edge of the crenkil. The crenkil had the tip?""", None],
 ["""John ate berries with the edge of a crenkil. John is a crenkil?""", None],
 ["""John ate berries with the edge of a crenkil. John is an edge?""", None],
 ["""John ate berries with the edge of a crenkil. Berries have an edge?""", None, [{'berries': 'big objects'}]],
 ["""Bears eat berries in a forest. Bears eat berries in a forest?""", True],
 ["""Bears eat berries in a forest. Bears eat berries in a big forest?""", None],
 ["""Bears eat berries in a forest. Bears eat berries in a field?""", None],
 ["""Bears do not eat berries in a forest. Bears eat berries in a forest?""", False],
 ["""Bears ate berries in a forest. Bears did not eat berries in a forest?""", False],
 ["""Bears ate berries in a forest. Bears did not eat berries in a field?""", None],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest which was bought by her?""", True],
 ["""Bears ate nice berries in a big forest which was seen by Mary. Bears ate berries in the forest which was seen by her?""", True],
 ["""Bears ate nice berries in a big forest which was bought by Mike. Bears ate berries in the forest which was bought by him?""", True],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest which was bought by a man?""", None],
 ["""Bears ate nice berries in a big forest which was bought by Mary. Bears ate berries in the forest?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. The forest was bought by Mary?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in a forest which was seen by Mary. Bears ate berries in the forest seen by Mary?""", True],
 ["""Bears ate berries in a forest which was bought by Mike. Bears ate berries in the forest bought by Mike?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was seen by Mary. Mary saw the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was bought by Mike. Mike bought the forest where the bears ate?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears drank?""", None],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate berries?""", True],
 ["""Bears ate berries in a forest which was bought by Mary. Mary bought the forest where the bears ate honey?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a forest with a spoon?""", True],
 ["""John ate berries in a forest with a spoon. John ate berries in a field?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a nice forest with a spoon?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries in a nice forest?""", None],
 ["""John ate berries in a forest with a spoon. John ate berries with a spoon in a nice forest?""", None],
 ["""John ate berries with the help of a spoon. John ate berries with the help of a spoon?""", True],
 ["""John ate berries with the help of a spoon. John ate berries with the help of a spade?""", None],
 ["""John lives in a car which is red. The car is red?""", True],
 ["""John lives in a car which is red. The car is nice?""", None],
 ["""John lives in a car which is red. John lives in a red car?""", True],
 ["""John lives in a car which is red. John lives in a nice car?""", None],
 ["""John lives in a car which is red and was bought by Mary. The nice car was bought by Mary?""", None],
 ["""John lives in a car which is red and was bought by Mary. The car was bought by John?""", None],
 ["""John has a car which is nice and red. The car is red and nice?""", True],
 ["""John has a car which is nice and red. The red car is nice?""", True],
 ["""John has a car which is nice and red. The big car is nice?""", None],
 ["""John has a red car which is nice and big. The nice car is big and red?""", True],
 ["""John has a red car which is nice and big. The car is good?""", None],
 ["""John lives in a nice car which was red and was bought by Mary. John lives in a nice yellow car?""", None],
 ["""John lives in a nice car which was red and was bought by Mike. John lives in a car which was bought by Mike?""", True],
 ["""John lives in a car which is red and was bought by Mary. The car was bought by John?""", None],
 ["""John lives in a red car bought by Mary. Mary bought the car?""", True],
 ["""John lives in a red car bought by Mary. Mary bought the car where John lives?""", True],
 ["""John lives in a red car bought by Mary. Mary bought the car where John ate?""", None],
 ["""John lives in a red car bought by Mary. Mary bought the car where Mike lives?""", None],
 ["""John shot an elephant in his pyjamas. The elephant was in his pyjamas?""", None],
 ["""John shot an elephant in his pyjamas. John shot in his pyjamas?""", True],
 ["""Mike ate berries in the forest bought by Mary. Mike ate berries in the forest bought by Mary?""", True],
 ["""Mike ate berries in the forest bought by Mary. Mike ate berries in the forest bought by John?""", None],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest which was bought by Mary?""", True],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest which was bought by John?""", None],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest bought by Mary?""", True],
 ["""Mike ate berries in the forest which was bought by Mary. Mike ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in the forest bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in the forest bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest which was bought by Mary?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest which was bought by John?""", None],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest bought by Mary?""", True],
 ["""Bears ate berries in the forest which was bought by Mary. Bears ate berries in the forest bought by John?""", None],
 ["""Cars are red. Cars have crenkils. Cars are red and have crenkils?""", True],
 ["""Cars are red. Cars are red and have crenkils?""", None],
 ["""Cars have crenkils. Cars are red and have crenkils?""", None],
 ["""Cars are red and cool and have crenkils. Cars are red and cool and have crenkils?""", True],
 ["""Cars are red and cool and have crenkils. Cars have crenkils and are red and cool?""", True],
 ["""Cars are cool and have crenkils. Cars are red and cool and have crenkils?""", None],
 ["""Cars are red and cool. Cars have crenkils and are red and cool?""", None],
 ["""Cars have fenders. Cars have crenkils. Cars have crenkils and fenders?""", True],
 ["""Cars have fenders. Cars have crenkils and fenders?""", None],
 ["""Cars have crenkils. Cars have crenkils and fenders?""", None],
 ["""John is defeated. Mike is defeated?""", None],
 ["""John is defeated. John is defeated?""", True],
 ["""John is defeated. John is not defeated?""", False],
 ["""If an animal is cool and defeated then it is nice. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. John is nice?""", True],
 ["""If an animal is cool and defeated then it is nice. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. John is not nice?""", False],
 ["""If an animal is cool and defeated then it is nice. 
   John is an animal. John is cool. 
   Mike is an animal. Mike is cool. John is defeated. Mike is nice?""", None],
 ["""If an animal is cool and defeated then it is nice. 
   John is a cool defeated animal. 
   Mike is an animal. Mike is cool. John is nice?""", True],
 ["""If an animal is cool and defeated then it is nice. 
   John is a cool defeated animal. 
   Mike is an animal. Mike is cool. John is not nice?""", False],
 ["""If an animal is cool and defeated then it is nice. 
   John is a defeated animal. 
   Mike is an animal. Mike is cool. John is nice?""", None],
 ["""If someone is a bird and wounded then they are abnormal. John is wounded. John is a bird. John is abnormal?""", True],
 ["""If someone is a bird and wounded then they are abnormal. John is a bird. John is abnormal?""", None],
 ["""John was nice and defeated. John was nice and defeated?""", True],
 ["""John was nice and defeated. John was nice?""", True],
 ["""John was defeated. John was defeated?""", True],
 ["""John is defeated. John was defeated?""", None],
 ["""John was defeated. John is defeated?""", None],
 ["""John is defeated. John is defeated?""", True],
 ["""If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals. 
    John is badly defeated. John is weak?""", True],
 ["""If someone is a nice animal and badly defeated then they are weak. John and Mike are nice animals. 
    John is badly defeated. Mike is weak?""", None],
 ["""If someone is a nice animal and badly defeated then they are weak. John is a nice animal. 
    Mike is badly defeated. Mike is weak?""", None],
 ["""Muggles cannot disappear. Mr Dursley is a Muggle. Mr Dursley can disappear?""", False],
 ["""Muggles can not disappear. Mr Dursley is a Muggle. Mr Dursley can disappear?""", False],
 ["""Americans cannot disappear. Mr Dursley is an American. Mr Dursley can disappear?""", False],
 ["""Americans can not disappear. Mr Dursley is an American. Mr Dursley can disappear?""", False],
 ["""Catholics can not disappear. Mr Dursley is a catholic. Mr Dursley can disappear?""", False],
 ["""Dolezalek defeated Dole. Dolezalek defeated Dole?""", True],
 ["""Dolezalek defeated Dole. Dolezalek defeated Mike?""", None],
 ["""Dole was defeated by Dolezalek. Dole was defeated by Dolezalek?""", True],
 ["""Dole was defeated by Dolezalek. Dole was defeated by Mike?""", None],
 ["""Dolezalek defeated Dole. Dole was defeated by Dolezalek?""", True],
 ["""Dolezalek defeated Dole. Dole was defeated by Mike?""", None],
 ["""Dole was defeated by Dolezalek. Dolezalek defeated Dole?""", True],
 ["""Dole was defeated by Dolezalek. Mike defeated Dole?""", None],
 ["""The car is red. The car is red?""", True],
 ["""The car is red. The car is nice?""", None],
 ["""Sue is a true patriot. Sue is a true patriot?""", True],
 ["""Sue is a true patriot. Sue is a nice patriot?""", None],
 ["""Sue is a true patriot. Sue is a true driver?""", None],
 ["""We are in the barn. We are in the barn?""", True],
 ["""We are in the barn. We are on the barn?""", None],
 ["""Agatha is in trouble. Agatha is in trouble?""", True],
 ["""Agatha is in trouble. Agatha is in the barn?""", None],
 ["""Agatha is in trouble. Agatha is through trouble?""", None],
 ["""There is a ghost in the room. There is a ghost in the room?""", True],
 ["""There is a ghost in the room. A ghost is in the room?""", True],
 ["""There is a ghost in the room. There is a lamp in the room?""", None],
 ["""There is a ghost in the room. There is a ghost in the barn?""", None],
 ["""These links present the many viewpoints that existed. These links present the lemmas that existed?""", None],
 ["""John is nice. Is it true that John is nice?""", True],
 ["""John is nice. Is it false that John is nice?""", False],
 ["""John is nice. It is true that John is nice?""", True],
 ["""John is nice. Is it false that John is nice?""", False],
 ["""John smokes tobacco with a probability 10 percent. Does John smoke?""", None],
 ["""Ellen is fond of John. Ellen is afraid of who?""", None],
 ["""John is in the box at the red house. A box is at a house?""", True],
 ["""John is in the box at a red house. The box is at a house?""", True],
 ["""John is in the box at a red house. The red box is at a house?""", None],
 ["""John is in the box at a red house. The box is at a blue house?""", None],
 ["""John is in a box at the red house. A box is at a house?""", True],
 ["""John is in a box at the red house. A box is at a house?""", True],
 ["""John is in a box at the red house. The box is at a house?""", True],
 ["""John is in a box at the red house. A box is at the red house?""", True],
 ["""During 1800, John jumped in a house. During 1800, John jumped?""", True],
 ["""During 1800, John jumped in a house. During 1801, John jumped?""", None],
 ["""Nile's length is 80 kilometers. The length of Nile is 80 kilometers?""", True],
 ["""Nile's length is 80 kilometers. The length of Nile is 90 kilometers?""", False],
 ["""Car's length is 80 kilometers. The length of the car is 80 kilometers?""", True],
 ["""Car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""The car's length is 80 kilometers. The length of the car is 80 kilometers?""", True],
 ["""The car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""The red car's length is 80 kilometers. The length of the blue car is 80 kilometers?""", None],
 ["""The red car's length is 80 kilometers. The length of the car is 90 kilometers?""", False],
 ["""Emajogi's length is 80 kilometers. Emajogi's length is 80 kilometers?""", True],
 ["""Emajogi's length is 80 kilometers. Emajogi's length is 90 kilometers?""", False],
 ["""Emajogi's length is 80 kilometers. The length of Emajogi is 80 kilometers?""", True],
 ["""Emajogi's length is 80 kilometers. The length of Emajogi is 90 kilometers?""", False],
 ["""The length of Emajogi is 80 kilometers. Emajogi is 80 kilometers long?""", True],
 ["""The length of Emajogi is 80 kilometers. Emajogi is 90 kilometers long?""", False],
 ["""The nice Emajogi is 80 kilometers long. The nice Emajogi is 80 kilometers long?""", True],
 ["""The nice Emajogi is 80 kilometers long. The nice Emajogi is 90 kilometers long?""", False],
 ["""The red straw is 10 meters long. The red straw is 10 meters long?""", True],
 ["""The red straw is 10 meters long. The red straw is 20 meters long?""", False],
 ["""John has the length 2 meters. John is 2 meters long?""", True],
 ["""John has the length 2 meters. John is 3 meters long?""", False],
 ["""John has length of 2 meters. John is 2 meters long?""", True],
 ["""John has length of 2 meters. John is 3 meters long?""", False],
 ["""John's length is 2 meters. John is 2 meters long?""", True],
 ["""The price of the red car is 2000 dollars. The price of the red car is 2000 dollars?""", True],
 ["""The price of the red car is 2000 dollars. The price of the red car is 3000 dollars?""", False],
 ["""The price of the red car is 2000 dollars. The price of the red car is 2000 crenkils?""", None],
 ["""The red car costs 2000 dollars. The price of the red car is 2000 dollars?""", True],
 ["""The red car costs 2000 dollars. The price of the red car is 3000 dollars?""", False],
 ["""The red car has a price of two dollars. The red car costs two dollars?""", True],
 ["""The red car has the price two dollars. The red car costs two dollars?""", True],
 ["""The red car has the price two dollars. The red car costs three dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The red car costs 3 dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The blue car costs 2 dollars?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The car costs three dollars?""", True],
 ["""The red car has the price two dollars. The blue car costs three dollars. The price of the red car equals the price of the blue car?""", False],
 ["""The red car has the price two dollars. The blue car costs three dollars. The price of the red car equals the price of the red car?""", True],
 ["""The red car has the price three dollars. The blue car costs three dollars. The price of the red car is the same as the price of the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The price of the red car is the same as the price of the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car costs as much as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car costs as much as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car is as expensive as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car is as expensive as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car is as cheap as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car is as cheap as the blue car?""", False],
 ["""The red car has the price three dollars. The blue car costs three dollars. The red car has the same price as the blue car?""", True],
 ["""The red car has the price three dollars. The blue car costs two dollars. The red car has the same price as the blue car?""", False],
 ["""The length of the red car is three meters. The blue car is 2 meters long. The red car has the same length as the blue car?""", False],
 ["""The length of the red car is three meters. The blue car is 2 meters long. The red car does not have the same length as the blue car?""", True],
 ["""The length of the red car is three meters. The blue car is 3 meters long. The red car has the same length as the blue car?""", True],
 ["""The length of the red car is three meters. The blue car is 3 meters long. The red car does not have the same length as the blue car?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is more than the length of the black car?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is less than the length of the black car?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is less than 2 meters?""", False],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters. 
      The length of the red car is over 2 meters?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters.   
      The length of the red car is more than 2 meters?""", True],
 ["""The length of the red car is 3 meters. The length of the black car is 5 meters.   
      The length of the red car is under 4 meters?""", True],
 ["""The length of the car is 3 meters. The bike has the same length as the car. The length of the bike is 3 meters?""", True],
 ["""The price of the car is 3 dollars. The bike has the same price as the car.  The price of the bike is 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 2 dollars?""", False],
 ["""The price of the car is 3 dollars. The bike is as expensive as the car. The price of the bike is 3 crenkils?""", None],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs 3 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The price of the bike is less than 20 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The price of the bike is more than 20 dollars?""", False],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs less than 20 dollars?""", True],
 ["""The price of the car is 3 dollars. The bike costs as much as the car. The bike costs more than 20 dollars?""", False],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs less than 20 tons?""", True],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs more than 2 tons?""", True],
 ["""The weight of the car is 3 tons. The bike weighs as much as the car. The bike weighs more than 20 tons?""", False],
 ["""The price of the car is below 20 dollars. The car costs less than 20 dollars?""", True],
 ["""The weight of the car is below 20 tons. The car weighs less than 20 tons?""", True],
 ["""The price of the car is above 20 dollars. The car costs more than 20 dollars?""", True],
 ["""The weight of the car is above 20 tons. The car weighs more than 20 tons?""", True]
]
